# This rule is not used by the project github-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over github.kuberik.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-controller
    app.kubernetes.io/managed-by: kustomize
  name: githubdeployment-admin-role
rules:
- apiGroups:
  - github.kuberik.com
  resources:
  - githubdeployments
  verbs:
  - '*'
- apiGroups:
  - github.kuberik.com
  resources:
  - githubdeployments/status
  verbs:
  - get
