# This rule is not used by the project github-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the github.kuberik.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-controller
    app.kubernetes.io/managed-by: kustomize
  name: githubdeployment-editor-role
rules:
- apiGroups:
  - github.kuberik.com
  resources:
  - githubdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.kuberik.com
  resources:
  - githubdeployments/status
  verbs:
  - get
