apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: default
type: Opaque
data:
  # Replace with base64 encoded GitHub token
  # echo -n "your-github-token" | base64
  token: eW91ci1naXRodWItdG9rZW4=



